version: 2
jobs:
  build-job:
    working_directory: ~/origin-spacebox
    docker:
      - image: circleci/node:8.11.0
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Mocha Test Suite
          command: 'npm run test'
  deploy-job:
    working_directory: ~/origin-spacebox
    docker:
      - image: circleci/node:8.11.0
    steps:
      - checkout
      - run:
          name: Install Now
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: Deploy using Now
          command: now -t ${NOW_TOKEN} && alias
workflows:
  version: 2
  build:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master